# CONFIG_LCD_USING_TFT_H080A11HDIFT4C30_V0_1 is not set
CONFIG_LCD_USING_TFT_CO5300=y
# CONFIG_BSP_USING_KEY1 is not set
CONFIG_RT_MAIN_THREAD_STACK_SIZE=32768
CONFIG_RT_MAIN_THREAD_PRIORITY=21
CONFIG_DFS_FILESYSTEMS_MAX=3
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_SERIAL_RB_BUFSZ=256
CONFIG_RT_USING_HWMAILBOX=y
CONFIG_RT_USING_MTD_DHARA=y
CONFIG_RT_USING_RYM=y
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_OUTPUT_FLOAT=y
# CONFIG_ULOG_USING_COLOR is not set
CONFIG_ULOG_OUTPUT_THREAD_NAME=y
CONFIG_RT_TIMER_THREAD_STACK_SIZE=4096
CONFIG_RT_USING_MEMHEAP=y
CONFIG_RT_USING_MEMHEAP_AS_HEAP=y
CONFIG_RT_USING_MEMTRACE=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_BLUETOOTH=y
CONFIG_USING_CELL_TRANSFORM=y
CONFIG_USING_BUTTON_LIB=y
CONFIG_BUTTON_MAX_NUM=4
CONFIG_USING_CPU_USAGE_PROFILER=y
CONFIG_PKG_USING_CJSON=y
CONFIG_PKG_USING_LITTLEVGL2RTT=y
CONFIG_LVGL_V9=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_PERF_MONITOR=y
CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_30=y
CONFIG_LV_FONT_MONTSERRAT_36=y
CONFIG_LV_FONT_MONTSERRAT_48=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_24=y
CONFIG_LV_FONT_FMT_TXT_LARGE=y
CONFIG_LV_CALENDAR_WEEK_STARTS_MONDAY=y
CONFIG_LV_USE_FS_STDIO=y
CONFIG_LV_FS_STDIO_LETTER=65
CONFIG_LV_FS_STDIO_PATH="/"
CONFIG_LV_USE_QRCODE=y
CONFIG_LV_USE_SNAPSHOT=y
CONFIG_LV_USE_IME_PINYIN=y
CONFIG_LV_DEF_REFR_PERIOD=16
CONFIG_CONFIG_LV_OS_RTTHREAD=y
CONFIG_LV_USE_CALENDAR_CHINESE=y
CONFIG_LV_FS_DEFAULT_DRIVER_LETTER=90
CONFIG_LV_USE_LODEPNG=y
CONFIG_LV_BIN_DECODER_RAM_LOAD=y
CONFIG_LV_USE_TINY_TTF=y
CONFIG_LV_TINY_TTF_FILE_SUPPORT=y
CONFIG_LV_TINY_TTF_CACHE_GLYPH_CNT=128
CONFIG_LV_USE_SYSMON=y
CONFIG_LV_USE_FILE_EXPLORER=y
CONFIG_CONFIG_LV_LOG_LEVEL_TRACE=y
CONFIG_LV_USING_FILE_RESOURCE=y
CONFIG_LV_FB_LINE_NUM=152
CONFIG_OPT_LEVEL_FAST=y
CONFIG_IMAGE_CACHE_IN_SRAM_SIZE=128000
